name: gliding_onboarding_screens
description: A highly customizable and animated onboarding screen for Flutter. Features include parallax effects, hero animations, built-in persistence, and a developer-friendly API for creating stunning app introductions.
version: 0.1.3
repository: https://github.com/Ayeshacode-s/animated-onboarding-screens.git
homepage:homepage: https://github.com/Ayeshacode-s/animated-onboarding-screens
environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.0
  flutter_animate: ^4.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/
